spring.application.name=shopping-cart-api

server.port=9193

spring.datasource.url=jdbc:mysql://localhost:3306/shopping_cart_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=MINkhant007#

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
#(create, update, create-drop, validate)
spring.jpa.hibernate.ddl-auto=update

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

api.prefix=/api/v1

auth.token.expirationInMils=3600000
auth.token.jwtSecret=cec23c74d5feb4793970c6afaf516f9278b5358c39b64e316a88d5a3d14fb328a072d29ede4538bd03e6672533c410782d53e1a7475f1b619ab6dbc39e8810b4
